In [1]:
import torch
import numpy as np

initilze Tensor
In two ways
Dirct from data

In [2]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)


From a Numpy array
tensor can be created from Numoy arry (and Vice Versa)

In [3]:
np_array=np.array(data)
x_np=torch.tensor(np_array)

From another tensor:
the new tensor retain the properites (shape,datatpe)of atrgumnet unless explicitly overriden

In [4]:
x_ones=torch.ones_like(x_data)
print(f'Ones Tensor:#\n{x_ones}\n')
x_rand=torch.rand_like(x_data,dtype=torch.float)
print(f'Random  Tensor:#\n{x_rand}\n')


Ones Tensor:#
tensor([[1, 1],
        [1, 1]])

Random  Tensor:#
tensor([[0.1186, 0.7477],
        [0.7649, 0.5705]])



what random or cinstant values:

shape is tuple of tensor dim ,In the funcation beow it ,it determines the dim of the output tensors

In [5]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f'Random Tensors: \n{rand_tensor}\n')
print(f'Ones Tensors: \n{ones_tensor}\n')
print(f'Zeros Tensors: \n{zeros_tensor}\n')



Random Tensors: 
tensor([[0.4715, 0.2569, 0.7621],
        [0.1107, 0.5245, 0.7580]])

Ones Tensors: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensors: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



Attributes of Tensors
Tensors atrributes describe their shpes,datatype,and the device on wich they are stored

In [6]:
tensor=torch.rand(3,4)
print(f'Shape of tensor:{tensor.shape}')
print(f'Datatype of tensor:{tensor.dtype}')
print(f'Device of tensor:{tensor.device}')

Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device of tensor:cpu


Operatoions of tensors
over 1200 opeartions ,includ artihmetic,linear algebra,matix mainplution(transposting,indecixg,sliceing)sampling and more
each of these can be run on CPU and Accelerateor such as CUDA,MPS,MTIA,beacusewe use coolab ,allocate an by going to runtime and chane it to GPU.
by defult,tensor ate cteared on CPU.we need explicitly move Tensors to Accelerator using(.to)method(after cheking for availability)Keep in mid copying large Tensors across devices can be expensive in term of time and memory

In [7]:
if torch.accelerator.is_available():
  tensor=tensor.to(torch.accelerator.current_accelerator())

In [8]:
tensor=torch.ones(3,4)
print(f'Fisrt Raw:{tensor[0]}')
print(f'Fisrt Column:{tensor[:,0]}')
print(f'last Column:{tensor[...,-1]}')
tensor[:,1]=0
print(tensor)

Fisrt Raw:tensor([1., 1., 1., 1.])
Fisrt Column:tensor([1., 1., 1.])
last Column:tensor([1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Joining Tensors you can use torch.catto concatenate a sequnce of tensors also given dim.See also torch.stack another tensor joining opreator that subtly different from torct.cat

In [9]:
t1=torch.cat([tensor,tensor,tensor],dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Arithmatic Tensors

In [11]:
y1=tensor @ tensor.T
y2=tensor.matmul(tensor.T)
y3=torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)

#Htis compytes the elments-wise product. z1,z2,z3, will have same value(Invo In CNN)
z1=tensor*tensor
z2=tensor.mul(tensor)
z3=torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])